# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_Li.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_app_main_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.home_background_4 = QtWidgets.QWidget(self.centralwidget)
        self.home_background_4.setStyleSheet("#home_background_4{\n"
"        background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgb(194, 231, 255), stop:1 rgb(175, 255, 182))\n"
"}\n"
"\n"
"\n"
"")
        self.home_background_4.setObjectName("home_background_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.home_background_4)
        self.horizontalLayout_11.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_33 = QtWidgets.QWidget(self.home_background_4)
        self.widget_33.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.widget_33.setObjectName("widget_33")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_33)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_33)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_7.addWidget(self.pushButton_17)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_7.addItem(spacerItem)
        self.homeButton = QtWidgets.QPushButton(self.widget_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.homeButton.setFont(font)
        self.homeButton.setStyleSheet("#homeButton {\n"
"    border: 1px solid #008C8C; /* 设置边框样式 */\n"
"    border-radius: 15px; /* 设置边框圆角大小 */\n"
"\n"
"}\n"
"\n"
"#homeButton:hover {\n"
"    background-color: #d3d3d3; /* 悬停状态 */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/home-filling.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon1)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_7.addWidget(self.homeButton)
        self.trainButton = QtWidgets.QPushButton(self.widget_33)
        self.trainButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.trainButton.setFont(font)
        self.trainButton.setStyleSheet("#trainButton {\n"
"    border: 1px solid #008C8C; /* 设置边框样式 */\n"
"    border-radius: 15px; /* 设置边框圆角大小 */\n"
"}\n"
"\n"
"#trainButton:hover {\n"
"    background-color: #d3d3d3; /* 悬停状态 */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/work-filling.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trainButton.setIcon(icon2)
        self.trainButton.setObjectName("trainButton")
        self.verticalLayout_7.addWidget(self.trainButton)
        self.statButton = QtWidgets.QPushButton(self.widget_33)
        self.statButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.statButton.setFont(font)
        self.statButton.setStyleSheet("#statButton {\n"
"    border: 1px solid #008C8C; /* 设置边框样式 */\n"
"    border-radius: 15px; /* 设置边框圆角大小 */\n"
"}\n"
"\n"
"#statButton:hover {\n"
"    background-color: #d3d3d3; /* 悬停状态 */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/history-filling.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statButton.setIcon(icon3)
        self.statButton.setObjectName("statButton")
        self.verticalLayout_7.addWidget(self.statButton)
        self.settingButton = QtWidgets.QPushButton(self.widget_33)
        self.settingButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.settingButton.setFont(font)
        self.settingButton.setStyleSheet("#settingButton {\n"
"    border: 1px solid #008C8C; /* 设置边框样式 */\n"
"    border-radius: 15px; /* 设置边框圆角大小 */\n"
"}\n"
"\n"
"#settingButton:hover {\n"
"    background-color: #d3d3d3; /* 悬停状态 */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/setting-filling.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingButton.setIcon(icon4)
        self.settingButton.setObjectName("settingButton")
        self.verticalLayout_7.addWidget(self.settingButton)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 3)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(4, 1)
        self.verticalLayout_7.setStretch(5, 1)
        self.horizontalLayout_11.addWidget(self.widget_33)
        self.stackedWidget = QtWidgets.QStackedWidget(self.home_background_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Login)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login_background = QtWidgets.QWidget(self.Login)
        self.login_background.setStyleSheet("#login_background{\n"
"        background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgb(194, 231, 255), stop:1 rgb(175, 255, 182))\n"
"}")
        self.login_background.setObjectName("login_background")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.login_background)
        self.horizontalLayout_4.setContentsMargins(150, 100, 150, 100)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_login = QtWidgets.QWidget(self.login_background)
        self.widget_login.setStyleSheet("#widget_login {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px; \n"
"}")
        self.widget_login.setObjectName("widget_login")
        self.label_background = QtWidgets.QLabel(self.widget_login)
        self.label_background.setGeometry(QtCore.QRect(0, -10, 381, 371))
        self.label_background.setStyleSheet("#label_background {\n"
"    border-radius:20px; \n"
"}")
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("../login.png"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.label = QtWidgets.QLabel(self.widget_login)
        self.label.setGeometry(QtCore.QRect(350, 40, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_login)
        self.label_2.setGeometry(QtCore.QRect(350, 90, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_login)
        self.label_3.setGeometry(QtCore.QRect(510, 110, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_login)
        self.label_4.setGeometry(QtCore.QRect(360, 180, 54, 12))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.widget_login)
        self.textEdit.setGeometry(QtCore.QRect(360, 200, 281, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.widget_login)
        self.label_5.setGeometry(QtCore.QRect(360, 250, 54, 12))
        self.label_5.setObjectName("label_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_login)
        self.textEdit_2.setGeometry(QtCore.QRect(360, 270, 281, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_login)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 310, 141, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.widget_login)
        self.horizontalLayout_3.addWidget(self.login_background)
        self.stackedWidget.addWidget(self.Login)
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.home)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_3.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.line = QtWidgets.QFrame(self.widget_3)
        self.line.setMinimumSize(QtCore.QSize(0, 2))
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("Line{\n"
"    background-color: #008C8C\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setStyleSheet("QWidget{\n"
"    background-color: #d3d3d3;\n"
"    border-radius: 15px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    margin-bottom: 10px;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(462, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setStyleSheet("QWidget{\n"
"    background-color: #d3d3d3;\n"
"    border-radius: 15px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_3.addWidget(self.widget_8, 1, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3.addWidget(self.widget_6, 1, 2, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_3.addWidget(self.widget_7, 1, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget_5)
        self.widget_9.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_3.addWidget(self.widget_9, 0, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget_5)
        self.widget_10.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_3.addWidget(self.widget_10, 0, 1, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.widget_5)
        self.widget_11.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_3.addWidget(self.widget_11, 0, 2, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.widget_5)
        self.widget_12.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_3.addWidget(self.widget_12, 0, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.home)
        self.gaming = QtWidgets.QWidget()
        self.gaming.setObjectName("gaming")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.gaming)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_14 = QtWidgets.QWidget(self.gaming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_14.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.line_2 = QtWidgets.QFrame(self.widget_14)
        self.line_2.setMinimumSize(QtCore.QSize(0, 2))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_2.setStyleSheet("Line{\n"
"    background-color: #008C8C\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_26 = QtWidgets.QWidget(self.widget_15)
        self.widget_26.setStyleSheet("QWidget{\n"
"    background-color: #d3d3d3;\n"
"    border-radius: 15px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"}")
        self.widget_26.setObjectName("widget_26")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_26)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_7.addWidget(self.widget_26)
        self.widget_25 = QtWidgets.QWidget(self.widget_15)
        self.widget_25.setStyleSheet("QWidget{\n"
"    background-color: #d3d3d3;\n"
"    border-radius: 15px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"}")
        self.widget_25.setObjectName("widget_25")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_25)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.widget_25)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.verticalLayout_4.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.widget_14)
        self.widget_16.setStyleSheet("QWidget{\n"
"    background-color: #d3d3d3;\n"
"    border-radius: 15px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"}")
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_21 = QtWidgets.QWidget(self.widget_16)
        self.widget_21.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_5.addWidget(self.widget_21, 1, 0, 1, 1)
        self.widget_23 = QtWidgets.QWidget(self.widget_16)
        self.widget_23.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_5.addWidget(self.widget_23, 1, 2, 1, 1)
        self.widget_24 = QtWidgets.QWidget(self.widget_16)
        self.widget_24.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_24.setObjectName("widget_24")
        self.gridLayout_5.addWidget(self.widget_24, 1, 3, 1, 1)
        self.widget_22 = QtWidgets.QWidget(self.widget_16)
        self.widget_22.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_22.setObjectName("widget_22")
        self.gridLayout_5.addWidget(self.widget_22, 1, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_5.addWidget(self.lineEdit_7, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 1)
        self.verticalLayout_4.addWidget(self.widget_16)
        self.horizontalLayout_6.addWidget(self.widget_14)
        self.stackedWidget.addWidget(self.gaming)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.settings)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_18 = QtWidgets.QWidget(self.settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_18.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_18)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_6.addWidget(self.lineEdit_8)
        self.line_3 = QtWidgets.QFrame(self.widget_18)
        self.line_3.setMinimumSize(QtCore.QSize(0, 2))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_3.setStyleSheet("Line{\n"
"    background-color: #008C8C\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.widget_19 = QtWidgets.QWidget(self.widget_18)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_27 = QtWidgets.QWidget(self.widget_19)
        self.widget_27.setStyleSheet("QWidget{\n"
"    background-color: #d3d3d3;\n"
"    border-radius: 15px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"}")
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_27)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_27)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_7.addWidget(self.lineEdit_9, 0, 0, 1, 1)
        self.patient_img = QtWidgets.QWidget(self.widget_27)
        self.patient_img.setStyleSheet("#patient_img{\n"
"    background-color: white\n"
"}")
        self.patient_img.setObjectName("patient_img")
        self.gridLayout_7.addWidget(self.patient_img, 1, 0, 1, 1)
        self.patient_info = QtWidgets.QWidget(self.widget_27)
        self.patient_info.setStyleSheet("#patient_info{\n"
"    background-color: white\n"
"}")
        self.patient_info.setObjectName("patient_info")
        self.gridLayout_7.addWidget(self.patient_info, 1, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 3)
        self.horizontalLayout_9.addWidget(self.widget_27)
        self.horizontalLayout_9.setStretch(0, 1)
        self.verticalLayout_6.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.widget_18)
        self.widget_20.setStyleSheet("QWidget{\n"
"    background-color: #d3d3d3;\n"
"    border-radius: 15px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"}")
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_20)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_20)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_8.addWidget(self.lineEdit_11, 0, 0, 1, 2)
        self.overviewButton = QtWidgets.QPushButton(self.widget_20)
        self.overviewButton.setMinimumSize(QtCore.QSize(0, 30))
        self.overviewButton.setStyleSheet("#overviewButton{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.overviewButton.setObjectName("overviewButton")
        self.gridLayout_8.addWidget(self.overviewButton, 1, 0, 1, 1)
        self.chart = QtWidgets.QWidget(self.widget_20)
        self.chart.setMinimumSize(QtCore.QSize(0, 150))
        self.chart.setStyleSheet("#chart{\n"
"    background-color:white;\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.chart.setObjectName("chart")
        self.gridLayout_8.addWidget(self.chart, 1, 1, 3, 1)
        self.gameOptionButton = QtWidgets.QPushButton(self.widget_20)
        self.gameOptionButton.setMinimumSize(QtCore.QSize(0, 30))
        self.gameOptionButton.setStyleSheet("#gameOptionButton{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.gameOptionButton.setObjectName("gameOptionButton")
        self.gridLayout_8.addWidget(self.gameOptionButton, 2, 0, 1, 1)
        self.gameOptionButton_2 = QtWidgets.QPushButton(self.widget_20)
        self.gameOptionButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.gameOptionButton_2.setStyleSheet("#gameOptionButton_2{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.gameOptionButton_2.setObjectName("gameOptionButton_2")
        self.gridLayout_8.addWidget(self.gameOptionButton_2, 3, 0, 1, 1)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_8.setColumnStretch(1, 3)
        self.verticalLayout_6.addWidget(self.widget_20)
        self.horizontalLayout_10.addWidget(self.widget_18)
        self.stackedWidget.addWidget(self.settings)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_34 = QtWidgets.QWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_34.sizePolicy().hasHeightForWidth())
        self.widget_34.setSizePolicy(sizePolicy)
        self.widget_34.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_34.setStyleSheet("QWidget{\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_34.setObjectName("widget_34")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_34)
        self.verticalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget_34)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_8.addWidget(self.lineEdit_12)
        self.line_4 = QtWidgets.QFrame(self.widget_34)
        self.line_4.setMinimumSize(QtCore.QSize(0, 2))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_4.setStyleSheet("Line{\n"
"    background-color: #008C8C\n"
"}")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_8.addWidget(self.line_4)
        self.widget_35 = QtWidgets.QWidget(self.widget_34)
        self.widget_35.setObjectName("widget_35")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_35)
        self.gridLayout_4.setContentsMargins(50, -1, 50, -1)
        self.gridLayout_4.setVerticalSpacing(15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 103, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem3, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 4, 2, 1, 1)
        self.setting_option_3 = QtWidgets.QWidget(self.widget_35)
        self.setting_option_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.setting_option_3.setStyleSheet("#setting_option_3{\n"
"    background-color: #DDDDDD\n"
"}")
        self.setting_option_3.setObjectName("setting_option_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.setting_option_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.brightness = QtWidgets.QLabel(self.setting_option_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.brightness.setFont(font)
        self.brightness.setStyleSheet("#brightness{\n"
"    background-color: #DDDDDD\n"
"}")
        self.brightness.setObjectName("brightness")
        self.horizontalLayout_15.addWidget(self.brightness)
        spacerItem5 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.brightnessSlider = QtWidgets.QSlider(self.setting_option_3)
        self.brightnessSlider.setStyleSheet("#brightnessSlider{\n"
"    background-color: #DDDDDD\n"
"}")
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.horizontalLayout_15.addWidget(self.brightnessSlider)
        self.gridLayout_4.addWidget(self.setting_option_3, 2, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 4, 0, 1, 1)
        self.setting_option_2 = QtWidgets.QWidget(self.widget_35)
        self.setting_option_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.setting_option_2.setStyleSheet("#setting_option_2{\n"
"    background-color: #DDDDDD\n"
"}")
        self.setting_option_2.setObjectName("setting_option_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.setting_option_2)
        self.horizontalLayout_14.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.language = QtWidgets.QLabel(self.setting_option_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.language.setFont(font)
        self.language.setStyleSheet("#language{\n"
"    background-color: #DDDDDD\n"
"}")
        self.language.setObjectName("language")
        self.horizontalLayout_14.addWidget(self.language)
        spacerItem7 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.langOption = QtWidgets.QComboBox(self.setting_option_2)
        self.langOption.setMinimumSize(QtCore.QSize(0, 23))
        self.langOption.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.langOption.setFont(font)
        self.langOption.setObjectName("langOption")
        self.langOption.addItem("")
        self.langOption.addItem("")
        self.horizontalLayout_14.addWidget(self.langOption)
        self.gridLayout_4.addWidget(self.setting_option_2, 1, 0, 1, 3)
        self.setting_option_1 = QtWidgets.QWidget(self.widget_35)
        self.setting_option_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.setting_option_1.setStyleSheet("#setting_option_1{\n"
"    background-color: #DDDDDD\n"
"}")
        self.setting_option_1.setObjectName("setting_option_1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.setting_option_1)
        self.horizontalLayout_12.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.edtion = QtWidgets.QLabel(self.setting_option_1)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.edtion.setFont(font)
        self.edtion.setStyleSheet("#edtion{\n"
"    background-color: #DDDDDD    \n"
"}")
        self.edtion.setObjectName("edtion")
        self.horizontalLayout_12.addWidget(self.edtion)
        self.edtionValue = QtWidgets.QLabel(self.setting_option_1)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.edtionValue.setFont(font)
        self.edtionValue.setStyleSheet("#edtionValue{\n"
"    background-color: #DDDDDD\n"
"}")
        self.edtionValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtionValue.setObjectName("edtionValue")
        self.horizontalLayout_12.addWidget(self.edtionValue)
        self.gridLayout_4.addWidget(self.setting_option_1, 0, 0, 1, 3)
        self.setting_option_5 = QtWidgets.QWidget(self.widget_35)
        self.setting_option_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.setting_option_5.setStyleSheet("#setting_option_5{\n"
"    background-color: #E73131\n"
"}")
        self.setting_option_5.setObjectName("setting_option_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.setting_option_5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.signOut = QtWidgets.QLabel(self.setting_option_5)
        self.signOut.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.signOut.setFont(font)
        self.signOut.setStyleSheet("#signOut{\n"
"    background-color: #E73131\n"
"}")
        self.signOut.setAlignment(QtCore.Qt.AlignCenter)
        self.signOut.setObjectName("signOut")
        self.horizontalLayout_16.addWidget(self.signOut)
        self.gridLayout_4.addWidget(self.setting_option_5, 4, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_35)
        self.horizontalLayout_13.addWidget(self.widget_34)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 4)
        self.horizontalLayout.addWidget(self.home_background_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_17.setText(_translate("MainWindow", " 导     航"))
        self.homeButton.setText(_translate("MainWindow", "主       页 "))
        self.trainButton.setText(_translate("MainWindow", "训练康复"))
        self.statButton.setText(_translate("MainWindow", "训练统计"))
        self.settingButton.setText(_translate("MainWindow", "系统设置"))
        self.label.setText(_translate("MainWindow", "UserLogin"))
        self.label_2.setText(_translate("MainWindow", "欢迎登录"))
        self.label_3.setText(_translate("MainWindow", "康复训练&管理系统"))
        self.label_4.setText(_translate("MainWindow", "用户名"))
        self.label_5.setText(_translate("MainWindow", "密码"))
        self.pushButton_6.setText(_translate("MainWindow", "登录"))
        self.lineEdit.setText(_translate("MainWindow", "  主页"))
        self.lineEdit_2.setText(_translate("MainWindow", "用户名：XXXXX"))
        self.lineEdit_3.setText(_translate("MainWindow", "ID: XXXXX"))
        self.lineEdit_4.setText(_translate("MainWindow", "康复训练"))
        self.lineEdit_5.setText(_translate("MainWindow", "训练目标"))
        self.lineEdit_6.setText(_translate("MainWindow", "难度梯度"))
        self.lineEdit_7.setText(_translate("MainWindow", "游戏"))
        self.lineEdit_8.setText(_translate("MainWindow", "患者详情"))
        self.lineEdit_9.setText(_translate("MainWindow", "患者信息"))
        self.lineEdit_11.setText(_translate("MainWindow", "训练汇总"))
        self.overviewButton.setText(_translate("MainWindow", "总览"))
        self.gameOptionButton.setText(_translate("MainWindow", "项目一"))
        self.gameOptionButton_2.setText(_translate("MainWindow", "项目二"))
        self.lineEdit_12.setText(_translate("MainWindow", "系统设置"))
        self.brightness.setText(_translate("MainWindow", "亮度"))
        self.language.setText(_translate("MainWindow", "语言"))
        self.langOption.setItemText(0, _translate("MainWindow", "简体中文"))
        self.langOption.setItemText(1, _translate("MainWindow", "English"))
        self.edtion.setText(_translate("MainWindow", "系统版本                                                                    "))
        self.edtionValue.setText(_translate("MainWindow", "V1.0.1"))
        self.signOut.setText(_translate("MainWindow", "退出登录"))
