# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frontend_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(986, 832)
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setGeometry(QtCore.QRect(9, 19, 921, 701))
        self.main_frame.setStyleSheet("#main_frame {\n"
"    background-color: rgb(239, 228, 255)\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.site_frame_1 = QtWidgets.QFrame(self.main_frame)
        self.site_frame_1.setGeometry(QtCore.QRect(10, 10, 161, 671))
        self.site_frame_1.setStyleSheet("#site_frame_1 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-left-radius: 10px; /* 设置左上角圆角 */\n"
"    border-bottom-left-radius: 10px; /* 设置左下角圆角 */\n"
"}")
        self.site_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.site_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.site_frame_1.setObjectName("site_frame_1")
        self.label = QtWidgets.QLabel(self.site_frame_1)
        self.label.setGeometry(QtCore.QRect(30, 20, 54, 16))
        self.label.setObjectName("label")
        self.user_info = QtWidgets.QPushButton(self.site_frame_1)
        self.user_info.setGeometry(QtCore.QRect(20, 70, 121, 24))
        self.user_info.setStyleSheet("#user_info{\n"
"    border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.user_info.setObjectName("user_info")
        self.settings = QtWidgets.QPushButton(self.site_frame_1)
        self.settings.setGeometry(QtCore.QRect(20, 620, 121, 24))
        self.settings.setStyleSheet("#settings {\n"
"    border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.settings.setObjectName("settings")
        self.training_statistic = QtWidgets.QPushButton(self.site_frame_1)
        self.training_statistic.setGeometry(QtCore.QRect(20, 580, 121, 24))
        self.training_statistic.setStyleSheet("#training_statistic {\n"
"        border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.training_statistic.setObjectName("training_statistic")
        self.rehabilition_training_button = QtWidgets.QPushButton(self.site_frame_1)
        self.rehabilition_training_button.setGeometry(QtCore.QRect(20, 540, 121, 24))
        self.rehabilition_training_button.setStyleSheet("#rehabilition_training_button {\n"
"        border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.rehabilition_training_button.setObjectName("rehabilition_training_button")
        self.patients_manage = QtWidgets.QPushButton(self.site_frame_1)
        self.patients_manage.setGeometry(QtCore.QRect(20, 500, 121, 24))
        self.patients_manage.setStyleSheet("#patients_manage {\n"
"        border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.patients_manage.setObjectName("patients_manage")
        self.label_2 = QtWidgets.QLabel(self.site_frame_1)
        self.label_2.setGeometry(QtCore.QRect(30, 500, 21, 16))
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_frame)
        self.stackedWidget.setGeometry(QtCore.QRect(170, 10, 741, 671))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.main_frame_2 = QtWidgets.QFrame(self.page)
        self.main_frame_2.setGeometry(QtCore.QRect(0, 0, 741, 671))
        self.main_frame_2.setStyleSheet("#main_frame_2 {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgb(194, 231, 255), stop:1 rgb(175, 255, 182));\n"
"    border-top-right-radius: 10px; /* 设置左上角圆角 */\n"
"    border-bottom-right-radius: 10px; /* 设置左下角圆角 */\n"
"}")
        self.main_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame_2.setObjectName("main_frame_2")
        self.re_targets = QtWidgets.QWidget(self.main_frame_2)
        self.re_targets.setGeometry(QtCore.QRect(20, 70, 301, 251))
        self.re_targets.setStyleSheet("#re_targets {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px; \n"
"}")
        self.re_targets.setObjectName("re_targets")
        self.re_targets_title = QtWidgets.QLabel(self.re_targets)
        self.re_targets_title.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.re_targets_title.setStyleSheet("#re_targets_title {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    \n"
"}")
        self.re_targets_title.setObjectName("re_targets_title")
        self.motor_coordination = QtWidgets.QPushButton(self.re_targets)
        self.motor_coordination.setGeometry(QtCore.QRect(10, 50, 281, 51))
        self.motor_coordination.setStyleSheet("#motor_coordination {\n"
"    background-color: rgb(238, 238, 238);\n"
"        border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.motor_coordination.setObjectName("motor_coordination")
        self.mind_training = QtWidgets.QPushButton(self.re_targets)
        self.mind_training.setGeometry(QtCore.QRect(10, 110, 281, 51))
        self.mind_training.setStyleSheet("#mind_training {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.mind_training.setObjectName("mind_training")
        self.static_strength = QtWidgets.QPushButton(self.re_targets)
        self.static_strength.setGeometry(QtCore.QRect(10, 170, 281, 51))
        self.static_strength.setStyleSheet("#static_strength {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-radius: 12px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(143, 143, 143);\n"
"}")
        self.static_strength.setObjectName("static_strength")
        self.training_settings = QtWidgets.QWidget(self.main_frame_2)
        self.training_settings.setGeometry(QtCore.QRect(340, 70, 381, 251))
        self.training_settings.setStyleSheet("#training_settings {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.training_settings.setObjectName("training_settings")
        self.training_settings_title = QtWidgets.QLabel(self.training_settings)
        self.training_settings_title.setGeometry(QtCore.QRect(0, 0, 381, 31))
        self.training_settings_title.setStyleSheet("#training_settings_title {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    \n"
"}")
        self.training_settings_title.setObjectName("training_settings_title")
        self.widget_4 = QtWidgets.QWidget(self.training_settings)
        self.widget_4.setGeometry(QtCore.QRect(210, 40, 161, 201))
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(self.training_settings)
        self.widget_5.setGeometry(QtCore.QRect(20, 40, 171, 201))
        self.widget_5.setObjectName("widget_5")
        self.pushButton = QtWidgets.QPushButton(self.widget_5)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 141, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 141, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 100, 141, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 150, 131, 24))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_3 = QtWidgets.QLabel(self.main_frame_2)
        self.label_3.setGeometry(QtCore.QRect(340, 20, 71, 31))
        self.label_3.setObjectName("label_3")
        self.widget_3 = QtWidgets.QWidget(self.main_frame_2)
        self.widget_3.setGeometry(QtCore.QRect(70, 380, 631, 221))
        self.widget_3.setObjectName("widget_3")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("")
        self.page_3.setObjectName("page_3")
        self.patients_management = QtWidgets.QWidget(self.page_3)
        self.patients_management.setGeometry(QtCore.QRect(-1, -1, 741, 671))
        self.patients_management.setStyleSheet("#patients_management {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgb(194, 231, 255), stop:1 rgb(175, 255, 182))\n"
"}")
        self.patients_management.setObjectName("patients_management")
        self.widget_6 = QtWidgets.QWidget(self.patients_management)
        self.widget_6.setGeometry(QtCore.QRect(50, 50, 641, 491))
        self.widget_6.setObjectName("widget_6")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("#training_frame {\n"
"    background: qlineargradient(spread:pad, x1:0.4, y1:0.3, x2:1, y2:1, stop:0 rgb(255, 255, 255), stop:1 rgb(240, 228, 255));\n"
"    border-top-right-radius: 10px; /* 设置左上角圆角 */\n"
"    border-bottom-right-radius: 10px; /* 设置左下角圆角 */\n"
"}")
        self.page_2.setObjectName("page_2")
        self.training_frame = QtWidgets.QFrame(self.page_2)
        self.training_frame.setGeometry(QtCore.QRect(-1, -1, 741, 671))
        self.training_frame.setStyleSheet("#training_frame {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgb(194, 231, 255), stop:1 rgb(175, 255, 182))\n"
"}")
        self.training_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.training_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.training_frame.setObjectName("training_frame")
        self.widget = QtWidgets.QWidget(self.training_frame)
        self.widget.setGeometry(QtCore.QRect(19, 29, 711, 631))
        self.widget.setObjectName("widget")
        self.verticalSlider = QtWidgets.QSlider(self.widget)
        self.verticalSlider.setGeometry(QtCore.QRect(690, 0, 20, 631))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 681, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-1, 10, 681, 151))
        self.widget_2.setObjectName("widget_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 70, 75, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 70, 75, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 70, 75, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(570, 70, 75, 24))
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "导航"))
        self.user_info.setText(_translate("Form", "PushButton"))
        self.settings.setText(_translate("Form", "系统设置"))
        self.training_statistic.setText(_translate("Form", "训练统计"))
        self.rehabilition_training_button.setText(_translate("Form", "康复训练"))
        self.patients_manage.setText(_translate("Form", "患者管理"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.re_targets_title.setText(_translate("Form", "训练目标"))
        self.motor_coordination.setText(_translate("Form", "运动协调"))
        self.mind_training.setText(_translate("Form", "思维训练"))
        self.static_strength.setText(_translate("Form", "静态力量"))
        self.training_settings_title.setText(_translate("Form", "训练参数"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.pushButton_8.setText(_translate("Form", "PushButton"))
        self.label_3.setText(_translate("Form", "训练设置"))
        self.pushButton_4.setText(_translate("Form", "训练报告"))
        self.pushButton_5.setText(_translate("Form", "评估报告"))
        self.pushButton_6.setText(_translate("Form", "导出"))
        self.pushButton_7.setText(_translate("Form", "删除"))
