# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_background = QtWidgets.QWidget(self.centralwidget)
        self.login_background.setGeometry(QtCore.QRect(20, 10, 921, 641))
        self.login_background.setAutoFillBackground(False)
        self.login_background.setStyleSheet("#login_background{\n"
"        background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgb(194, 231, 255), stop:1 rgb(175, 255, 182))\n"
"}")
        self.login_background.setObjectName("login_background")
        self.widget_login = QtWidgets.QWidget(self.login_background)
        self.widget_login.setGeometry(QtCore.QRect(50, 100, 781, 451))
        self.widget_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_login.setAutoFillBackground(True)
        self.widget_login.setStyleSheet("#widget_login {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px; \n"
"}")
        self.widget_login.setObjectName("widget_login")
        self.label_background = QtWidgets.QLabel(self.widget_login)
        self.label_background.setGeometry(QtCore.QRect(0, -10, 501, 461))
        self.label_background.setStyleSheet("#label_background {\n"
"    border-radius:20px; \n"
"}")
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("C:/Users/Xiang/Desktop/素材/208页面设计/login.png"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.label = QtWidgets.QLabel(self.widget_login)
        self.label.setGeometry(QtCore.QRect(490, 60, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_login)
        self.label_2.setGeometry(QtCore.QRect(450, 110, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_login)
        self.label_3.setGeometry(QtCore.QRect(610, 130, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_login)
        self.label_4.setGeometry(QtCore.QRect(460, 180, 54, 12))
        self.label_4.setObjectName("label_4")
        self.user_id = QtWidgets.QTextEdit(self.widget_login)
        self.user_id.setGeometry(QtCore.QRect(460, 200, 281, 31))
        self.user_id.setObjectName("user_id")
        self.label_5 = QtWidgets.QLabel(self.widget_login)
        self.label_5.setGeometry(QtCore.QRect(460, 240, 54, 12))
        self.label_5.setObjectName("label_5")
        self.password = QtWidgets.QTextEdit(self.widget_login)
        self.password.setGeometry(QtCore.QRect(460, 260, 281, 31))
        self.password.setObjectName("password")
        self.login_pushButton = QtWidgets.QPushButton(self.widget_login)
        self.login_pushButton.setGeometry(QtCore.QRect(660, 310, 75, 23))
        self.login_pushButton.setObjectName("login_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "UserLogin"))
        self.label_2.setText(_translate("MainWindow", "欢迎登录"))
        self.label_3.setText(_translate("MainWindow", "康复训练&管理系统"))
        self.label_4.setText(_translate("MainWindow", "用户名"))
        self.label_5.setText(_translate("MainWindow", "密码"))
        self.login_pushButton.setText(_translate("MainWindow", "登录"))
